import { type } from 'arktype'

export const track = type({
  '+': 'reject',
  'artwork_url': 'string.url | null',
  'caption': 'string | null',
  'commentable': 'boolean',
  'comment_count': 'number | null',
  'created_at': 'string.date',
  'description': 'string | null',
  'downloadable': 'boolean',
  'download_count': 'number | null',
  'duration': 'number',
  'full_duration': 'number',
  'embeddable_by': '"all" | "none" | "me"',
  'genre': 'string | null',
  'has_downloads_left': 'boolean',
  'id': 'number',
  'kind': '"track"',
  'label_name': 'null | string',
  'last_modified': 'string.date',
  'license': 'string',
  'likes_count': 'number | null',
  'permalink': 'string',
  'permalink_url': 'string.url',
  'playback_count': 'number | null',
  'public': 'boolean',
  'publisher_metadata': type.null.or({
    id: 'number',
    urn: 'string',
  }),
  'purchase_title': 'string | null',
  'purchase_url': 'string.url | null',
  'release_date': 'string | null',
  'reposts_count': 'number',
  'secret_token': 'null|string',
  'sharing': '"public" | "private"',
  'state': '"finished" | "processing"',
  'streamable': 'boolean',
  'tag_list': 'string',
  'title': 'string',
  'uri': 'string.url',
  'urn': 'string',
  'user_id': 'number',
  'visuals': type.null.or({
    urn: 'string',
    enabled: 'boolean',
  }),
  'waveform_url': 'string.url',
  'display_date': 'string.date',
  'media': {
    transcodings: type({
      url: 'string.url',
      preset: '"opus_0_0" | "aac_160k" | "mp3_0_0" | "abr_sq" | "mp3_1_0" | "mp3_0_1" | "mp3_standard"',
      duration: 'number',
      snipped: 'boolean',
      format: {
        protocol: '"hls" | "progressive" | "ctr-encrypted-hls" | "cbc-encrypted-hls"',
        mime_type:
          `'audio/mp4; codecs="mp4a.40.2"'
          |'audio/mpegurl'
          |'audio/mpeg'
          |'audio/ogg; codecs="opus"'`,
      },
      quality: '"sq"',
      is_legacy_transcoding: 'boolean',
    }).array(),
  },
  'station_urn': 'string',
  'station_permalink': 'string',
  'track_authorization': 'string',
  'monetization_model': '"AD_SUPPORTED" | "BLACKBOX" | "NOT_APPLICABLE" | "SUB_HIGH_TIER"',
  'policy': '"MONETIZE" | "BLOCK" | "SNIP" | "ALLOW"',
  'user': {
    'avatar_url': 'string.url',
    'city': 'string | null',
    'comments_count?': 'number',
    'country_code': 'string | null',
    'created_at?': 'string.date',
    'creator_subscriptions?': [
      {
        product: {
          id: 'string',
        },
      },
    ],
    'creator_subscription?': {
      product: {
        id: 'string',
      },
    },
    'description?': 'string | null',
    'followers_count': 'number',
    'followings_count?': 'number',
    'first_name': 'string',
    'full_name': 'string',
    'groups_count?': 'number',
    'id': 'number',
    'kind': '"user"',
    'last_modified': 'string.date',
    'last_name': 'string',
    'likes_count?': 'number',
    'playlist_likes_count?': 'number',
    'permalink': 'string',
    'permalink_url': 'string.url',
    'playlist_count?': 'number',
    'reposts_count?': 'number | null',
    'track_count?': 'number',
    'uri': 'string.url',
    'urn': 'string',
    'username': 'string',
    'verified': 'boolean',
    'visuals?': type.null.or({
      urn: 'string',
      enabled: 'boolean',
      visuals: [
        {
          urn: 'string',
          entry_time: 'number',
          visual_url: 'string.url',
        },
      ],
      tracking: 'null',
    }),
    'badges': {
      pro: 'boolean',
      creator_mid_tier: 'boolean',
      pro_unlimited: 'boolean',
      verified: 'boolean',
    },
    'station_urn': 'string',
    'station_permalink': 'string',
    'date_of_birth?': 'string | null',
  },
})

export type Track = typeof track.infer
