import { user } from './user'
import { type } from 'arktype'

export const track = type({
	'+': 'reject',
	artwork_url: 'string.url | null',
	caption: 'string | null',
	commentable: 'boolean',
	'comment_count?': 'number | null',
	created_at: 'string.date',
	description: 'string | null',
	downloadable: 'boolean',
	'download_count?': 'number | null',
	duration: 'number',
	full_duration: 'number',
	embeddable_by: "'all'|'none'|'me'",
	'genre?': 'string | null',
	has_downloads_left: 'boolean',
	id: 'number',
	kind: "'track'",
	label_name: 'string | null',
	last_modified: 'string.date',
	license: 'string',
	'likes_count?': 'number | null',
	permalink: 'string',
	permalink_url: 'string',
	'playback_count?': 'number | null',
	public: 'boolean',
	publisher_metadata: type({
		id: 'number',
		urn: 'string',
		artist: 'string?',
		publisher: 'string?',
		album_title: 'string?',
		contains_music: 'boolean?',
		upc_or_ean: 'string?',
		iswc: 'string?',
		isrc: 'string?',
		explicit: 'boolean?',
		p_line: 'string?',
		p_line_for_display: 'string?',
		c_line: 'string?',
		c_line_for_display: 'string?',
		writer_composer: 'string?',
		release_title: 'string?',
	}).or('null'),
	purchase_title: 'string | null',
	purchase_url: 'string.url | null',
	release_date: 'string | null',
	reposts_count: 'number',
	secret_token: 'string | null',
	sharing: "'public'|'private'",
	state: "'finished'|'processing'",
	streamable: 'boolean',
	tag_list: 'string',
	title: 'string',
	uri: 'string',
	urn: 'string',
	user_id: 'number',
	visuals: type({
		urn: 'string',
		enabled: 'boolean',
		visuals: [
			{
				urn: 'string',
				entry_time: 'number',
				visual_url: 'string',
				link: 'string?',
			},
		],
		tracking: 'null',
	}).or('null'),
	waveform_url: 'string',
	display_date: 'string',
	media: {
		transcodings: type({
			url: 'string',
			preset:
				"'opus_0_0'|'aac_160k'|'mp3_0_0'|'abr_sq'|'mp3_1_0'|'mp3_0_1'|'mp3_standard'",
			duration: 'number',
			snipped: 'boolean',
			format: {
				protocol: "'hls'|'progressive'|'ctr-encrypted-hls'|'cbc-encrypted-hls'",
				mime_type:
					"'audio/mp4; codecs=\"mp4a.40.2\"'|'audio/mpegurl'|'audio/mpeg'|'audio/ogg; codecs=\"opus\"'",
			},
			quality: "'sq'",
			is_legacy_transcoding: 'boolean',
		}).array(),
	},
	station_urn: 'string',
	station_permalink: 'string',
	track_authorization: 'string',
	monetization_model:
		"'AD_SUPPORTED'|'BLACKBOX'|'NOT_APPLICABLE'|'SUB_HIGH_TIER'",
	policy: "'MONETIZE'|'BLOCK'|'SNIP'|'ALLOW'",
	user,
})

export type Track = typeof track.infer
